import React from "react";
import EventSchedule from "../../components/EventSchedule";
import Head from "next/head";

const SinglePage = () => {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>CalenderCard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex-col md:mx-4 lg:flex items-center mx-auto my-0 ease-in-out md:py-24">
        <EventSchedule />
      </main>
    </div>
  );
};

export default SinglePage;
