import Head from "next/head";
import EventCard from "../components/EventCard";

export default function Home() {
  const eventLists = [
    {
      id: 1,
      title: "30 Min Meeting",
      allocatedTime: "30 Minutes",
      eventType: "1-on-1",
      slugPath: "bmnepaltest/30min",
      timeTag:"30m"
    },
    {
      id: 2,
      title: "15 Min Meeting",
      allocatedTime: "15 Minutes",
      eventType: "1-on-1",
      slugPath: "bmnepaltest/15min",
      timeTag:"15m"
    },
  ];
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Cal Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl py-24 px-4 mx-auto">
        <div className="mb-8 text-center">
          <h1 className="font-cal mb-1 text-3xl text-neutral-900 dark:text-white font-medium">
            Saroj Subedi
          </h1>
          <p className="dark:text-darkgray-600 text-s text-neutral-500">test</p>
        </div>
        <div className="rounded-md  border border-neutral-200 dark:border-neutral-700 dark:hover:border-neutral-600">
          {eventLists.map((event) => (
            <EventCard key={event.id} event={event} />
          ))}
        </div>
      </main>
    </div>
  );
}
